# Generated by Django 5.2.3 on 2025-06-15 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_userprofile_user_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replying_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_received', to='comments.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.userprofile'),
        ),
    ]
